version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    
    working_directory: ~/circleci

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            python manage.py